const dummyParkData = [
  {
    id: 288242,
    name: 'Sam Houston Jones State Park',
    url: 'https://www.singletracks.com/bike-trails/sam-houston-jones-state-park/',
    length: '7.0',
    description:
      "Winding single track thru forest with lots of small hills. Many smaller loops off the main trail, you may miss the best riding, so explore them - you can't get lost.",
    directions:
      'Moss Bluff is just North of Lake Charles in SW LA.  Follow the signs to Sam Houston Jones State Park.  There are many trailheads. Most access the trail at the deer pen or boat launch.',
    city: 'Moss Bluff',
    region: 'Louisiana',
    country: 'United States',
    lat: '30.29732',
    lon: '-93.26926',
    difficulty: 'Intermediate',
    features: null,
    rating: 4,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2015/12/mobile-1450142590-orig.jpg',
  },
  {
    id: 275742,
    name: 'Westside',
    url: 'https://www.singletracks.com/bike-trails/westside-12564/',
    length: '8.0',
    description:
      'A network of fire trails that can me short or long depending on the route chosen.',
    directions: 'My House',
    city: 'Deridder',
    region: 'Louisiana',
    country: 'United States',
    lat: '30.84456',
    lon: '-93.32754',
    difficulty: 'Easiest',
    features: 'Night riding allowed',
    rating: 3.5,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2016/12/15,740955_10153983577041916_5025169972229548547_n-orig.jpg',
  },
  {
    id: 288245,
    name: 'Chicot State Park',
    url: 'https://www.singletracks.com/bike-trails/chicot-state-park/',
    length: '23.0',
    description:
      "The trail is a challenge mainly for it's distance.  The first 4 or five mile section (riding the trail clockwise) is fairly technical, it then is a nice singletrack with a few short hills.  It is very well marked, but bring water and food (none on the trail), the whole loop will take about 3 hours.<BR>",
    directions:
      'You can access the trail head just in Chicot State Park.  Ask for a free map at the entrance station.',
    city: 'Outside Ville Platte',
    region: 'Louisiana',
    country: 'United States',
    lat: '30.79258',
    lon: '-92.27960',
    difficulty: 'Intermediate',
    features: null,
    rating: 4,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2003/01/243-1184503073-orig.jpg',
  },
  {
    id: 282461,
    name: 'Martin Dies, Jr. State Park',
    url: 'https://www.singletracks.com/bike-trails/martin-dies-jr-state-park/',
    length: '16.0',
    description:
      'Martin Dies, Jr. State Park is rich in scenery and wildlife for visitors to enjoy. Paddling down the river is a favorite here but other activities include hiking, boating, fishing, swimming, mountain biking and camping.',
    directions:
      'To reach the park from U.S. Highway 69, travel 17 miles east from Woodville on U.S. Highway 190. From U.S. Highway 96, travel 12 miles west from Jasper on U.S. Highway 190. Or from Houston, take U.S. Highway 59 north to Livingston, and then travel east on U.S. Highway 190 for 65 miles to the park via Park Road 48.',
    city: 'Jasper',
    region: 'Texas',
    country: 'United States',
    lat: '30.84904',
    lon: '-94.16480',
    difficulty: '',
    features: null,
    rating: 0,
    thumbnail: null,
  },
  {
    id: 288247,
    name: 'Acadiana Park',
    url: 'https://www.singletracks.com/bike-trails/acadiana-park/',
    length: '4.0',
    description:
      'There are around six to ten trails to ride on. They are single track and fairly narrow. There are some obstacles. There are just a few hills. Total area may be one to two miles of tracks. It is a pretty good ride for beginners as there are only one or two tough spots. The trails are in pretty thick woods. Lots of roots to ride over. Also a few low points collect water after a rain, this can be a challenge...  The trail is free to the public. No restrictions on times to ride. It is usually not crowded...',
    directions:
      'From Interstate 10, exit Evangeline Throughway, south, Go to the first red light which is Willow. Take a left on Willow. Go to Louisiana Ave. Take a left. Go to first stop sign. Take a right here(Alexander). Go straight to Acadiana Park. Park behind the tennis courts. The trails are behind the courts.',
    city: 'Lafayette',
    region: 'Louisiana',
    country: 'United States',
    lat: '30.25336',
    lon: '-91.98393',
    difficulty: 'Beginner',
    features: 'Drinking water, Restrooms',
    rating: 3.79,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2018/11/20181118_154457-orig-scaled.jpg',
  },
  {
    id: 288239,
    name: 'Wild Azalea Trail',
    url: 'https://www.singletracks.com/bike-trails/wild-azalea-trail/',
    length: 24,
    description:
      'Extremely diverse 24+ miles of single track. Lots of connections and trails that branch off of it. Has about 7 different parking areas, and each one offers a different terrain. Some have very easy up and down trails. Some have really fast descents, long climbs, choppy descents, jumps, berms, etc. for skill levels.',
    directions:
      'From Baton Rouge, take I-10 west and cross over the bridge to Lafayette. Exit on US Highway 190 west. Travel approximately 15-20 miles until you reach La 71. Follow 71 north until you think you are going to die (around 75-100 mi.). When you get to the Alexandria area, switch to La 28 west. You will be heading toward Leesville (and should see some signs).',
    city: 'Alexandria',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.15182',
    lon: '-92.51842',
    difficulty: 'Intermediate',
    features: null,
    rating: 4.08,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2013/05/WP_20130427_053-0-orig.jpg',
  },
  {
    id: 280921,
    name: 'Wild Azalea Trail',
    url: 'https://www.singletracks.com/bike-trails/wild-azalea-trail-7720/',
    length: '26.0',
    description:
      "Wide singletrack that runs through remote forest. a few creek crossings. This trail route has some nice single track, good climbs, some double wide trails, some good pedaling sections, and some great down hills. There aren't many rocks or roots in the trail, a few roots on the steeper climbs, the biggest obstacles are probably fallen trees, but the trail is kept up well so there are not a lot of those either. There are some spots of sand on the trail to be ready for. The trail passes kincaid lake and there a few loops around the lake that break off of the Azalea Trail. The trail also intersects with the Lakeshore trail at Kincaid Lake, which is at the Kincaid East landing is a little easier and doesn't have as many rooty sections and is a little flatter.",
    directions:
      'From Alexandria go Hwy 28 west to Gardner at flashing light take left, go 1/4 mile take another left Heading towards Valentine Lake Recreation Area., the trailhead is right near the entrance to Valentines Lake camp grounds on your left. ( You can just follow the Forest service signs to the Camp ground from Hwy 28 west) The trail meanders through thewoods and comes out in Woodworth.',
    city: 'Alexandria',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.23937',
    lon: '-92.68401',
    difficulty: '',
    features: null,
    rating: 3,
    thumbnail: null,
  },
  {
    id: 282544,
    name: 'East Boat Ramp Trail',
    url: 'https://www.singletracks.com/bike-trails/east-boat-ramp-trail/',
    length: '30.0',
    description:
      'Starting from the East Boat Ramp, there is about 7 miles of lakeshore singletrack. This side is a bit more challenging than the West Lake Loop but it also more fun. You will reach a very long bridge that crosses the backwater of the lake.  From this bridge you can either go left (this portion is the Lamotte Trail) toward the Azalea Trail which is one mile away or right toward the West Kincaid Lakeshore Trail which is about 3 miles away.  Wild Azalea is another 25 miles of singletrack. The West Kincaid Lake Loop is about 8 miles.  The map shows the East singletrack and a right turn after the bridge, taking Lamotte to the West Kincaid Loop.  This out and back would be about 28 miles if you were to follow those, directions out to the loop, completing one loop, and doubling back the way you came.  There are endless miles to be thrown in if the Wild Azalea is included.  For drinking water, there is a spigot at the Recreation area on the West side that is always available.  This happens to be the halfway point of the out and back listed above.  If you are facing the beach at the swimming area, follow the sidewalk path down by the water to the left about 100 yards.',
    directions:
      'From Hwy 28 West, travel to Messina Rd.  Follow Messina for 2 miles looking for the East Boat Ramp on the right.  Ample parking but there is a $2 fee. The trailhead listed on the map is the Evangeline Camp which is about 5 miles further down Messina Rd and has free parking. Evangeline Camp is on the Wild Azalea Trail which has two different spurs leading to Kincaid.  Each spur is well marked with a sign.',
    city: 'Alexandria',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.23425',
    lon: '-92.60867',
    difficulty: '',
    features: null,
    rating: 0,
    thumbnail: null,
  },
  {
    id: 280838,
    name: 'Kincaid Lake',
    url: 'https://www.singletracks.com/bike-trails/kincade-lake/',
    length: '9.0',
    description:
      'Network of singletrack trails with a variety of difficulty and endurance. this is a beginner trail that has some elevation and more straight forward. Not very technical. There is camp grounds near here with a bike wash. This trail connect to the Lakeshore and Wild Azalea trails, which can be combined to create a longer ride.',
    directions:
      'From Alexandria: Go east on Hwy 28, south on Messina Rd., Start the trail at the East Boat Ramp.',
    city: 'Alexandria',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.24583',
    lon: '-92.60831',
    difficulty: 'Beginner',
    features: 'Drinking water, Restrooms',
    rating: 4,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2016/10/IMG_2299-orig-scaled.jpg',
  },
  {
    id: 284992,
    name: 'Kincaid Lakeshore Trail',
    url: 'https://www.singletracks.com/bike-trails/kincaid-lakshore-trail/',
    length: '25.0',
    description:
      'The trail is good single track. It seems like it gets a lot of use. It has short climbs and a few twisty parts. Nothing to serious. Some parts of the trail you can pick up and maintain some good speed and it makes the ride a blast. Anyone can ride this trail and have some good fun and good training value. You will not improve you technical skill on this trail but it is a good for ride for this area. The trail is maintained really well and decently marked. The trail also ties into Lamotte Creek trail and Wild Azelea trail. Seven miles one way. A really good trail for this area. You will not go home disappointed as I have with so many other trails in the area such as Wild Azelea. There are a few other trails in the national forest but I can not make a decent review because of the rain we have been getting in this area.',
    directions:
      'from Alexandria move to Highway 28 West. Once you start to move out of town you will see a small sign that says lake kincaid east boat ramp. Take a left at that road. The name of the road is Messina road. As you are moving south look for a sign that says east boat ramp and take a right at this road. Move to the end of the road and there will be a parking lot. The day use fee to park a vehicle there is 3 dollars. The trail head is marked. If you want to print out a map visit the kisatchie national forest website and view the Calcaseu unit link. You will see a print out for the entire area.',
    city: 'Alexandria',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.25819',
    lon: '-92.63281',
    difficulty: 'Intermediate',
    features: null,
    rating: 4.42,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2012/03/IMG_0679-0-orig.jpg',
  },
  {
    id: 275176,
    name: 'Caroline Dormon Trail',
    url: 'https://www.singletracks.com/bike-trails/caroline-dormon-trail/',
    length: '11.0',
    description:
      'The trail begins just East of the Bayou Campground.  There are many spots to camp and includes an outhouse.  There is also a creek nearby to swim in with the largest rapids in Louisiana. (Joking) Most of the trail is single track with a few portions of fire break.  There is a few sand pits along the way but nothing too difficult.  Also, this is one of the few trails in the area where you will find actual rocks.  Still this trail is not too technical.  At the end of the trail you come to another parking lot with an outhouse.  From there you must turn back for the only other trails in the area are for hiking and horseback only.',
    directions: 'Kisatchie Bayou Campground',
    city: 'Provencal',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.44487',
    lon: '-93.09251',
    difficulty: '',
    features: 'Fat biking allowed in winter, Restrooms',
    rating: 0,
    thumbnail: null,
  },
  {
    id: 284909,
    name: 'Cypress Bend Resort',
    url: 'https://www.singletracks.com/bike-trails/cypress-bend-resort/',
    length: '6.0',
    description:
      '5 possible loops ranging from 1-6 miles, can be ridden consecutively to create longer distances. Fast trail that requires strength and skill to conquer. Traverses over highest point in region to lakeside. Nine pine log bridges, 3 12 ,wide raised sections totaling 70 a lot of flow with off-camber descents and full range of turn angles.',
    directions:
      'google map: Cypress Bend Resort, 2000 Cypress Bend Parkway, Many, LA, 71449',
    city: 'Many',
    region: 'Louisiana',
    country: 'United States',
    lat: '31.43467',
    lon: '-93.69055',
    difficulty: 'Intermediate',
    features: null,
    rating: 2.86,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2014/01/mobile-1389328439-0-orig.jpg',
  },
  {
    id: 287490,
    name: 'Lake Fausse Pointe Trail System',
    url: 'https://www.singletracks.com/bike-trails/lake-fausse-pointe-trail-system/',
    length: '5.0',
    description:
      'Trail is actually a system of 3 loops.  There are a few elevation changes, but nothing over a few meters.  Trail can be fairly technical in some places with switchbacks, bridges over the swamp, and the roots running across the trail.  Maps can be obtained at the main gate ($2 day-use fee), trailhead, or Interpretive Center. To get any kinda mileage/time on the bike, ride all three loops.  Depending on the "dampness" of the trail near the beaver lodges, one may want to take advantage of the "Drier Alternate Route" thru the "Boy Scout Area".  Entire trail can get kinda wet, this is South Louisiana after all.  Good trail for beginner confidence boost.  And a blast for anyone who wants to test their suspension.',
    directions:
      'Starting on US Hwy 90 from either East or West, take the Cade/St. Martinville exit.  Take the first left, following signs for St. Martinville.  From St. Martinville, take LA 96 to LA 679, then to LA 3083. Turn right onto Levee Road for 8 miles.  Park entrance is on the right.',
    city: 'St. Martinville',
    region: 'Louisiana',
    country: 'United States',
    lat: '30.06183',
    lon: '-91.60718',
    difficulty: 'Beginner',
    features: null,
    rating: 2.89,
    thumbnail:
      'https://images.singletracks.com/blog/wp-content/uploads/2004/10/1046-1234146044-orig.jpg',
  },
];

module.exports = {
  dummyParkData,
};
